import {useMemo, useState, type ReactNode} from 'react';
import {ArrowRight, CheckCircle2, ChevronDown, Clock3, Grid2X2, Search, ShieldCheck, Sparkles, Zap} from 'lucide-react';

import {DemoSwitcher} from '../DemoRoot';
import {DEMO_AGENTS, DEMO_INSTALLATIONS, DEMO_WORKSPACE, matchesAgent, shortDate} from '../mockData';

type Tab = 'catalog' | 'workspace' | 'activity';

export default function SaasDemo() {
  const [tab, setTab] = useState<Tab>('catalog');
  const [query, setQuery] = useState('');
  const agents = useMemo(() => DEMO_AGENTS.filter((agent) => matchesAgent(agent, query)), [query]);
  return <div className="fixed inset-0 z-[150] overflow-y-auto bg-[#f7f9fc] text-slate-900">
    <header className="sticky top-0 z-10 border-b border-slate-200/80 bg-white/90 backdrop-blur flex items-center h-16 px-8"><div className="flex items-center gap-2 font-bold tracking-tight text-slate-900"><div className="h-8 w-8 rounded-lg bg-indigo-600 text-white flex items-center justify-center"><Sparkles size={15} /></div>NeKiro</div><nav className="ml-12 flex gap-1">{([['catalog', 'Catalog'], ['workspace', 'Workspace'], ['activity', 'Activity']] as const).map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`px-3 py-2 rounded-lg text-sm ${tab === id ? 'bg-indigo-50 text-indigo-700 font-semibold' : 'text-slate-500 hover:text-slate-900'}`}>{label}</button>)}</nav><div className="ml-auto flex items-center gap-3 text-xs text-slate-500"><span className="hidden sm:inline">{DEMO_WORKSPACE.ownerId}</span><div className="h-8 w-8 rounded-full bg-indigo-100 text-indigo-700 flex items-center justify-center font-semibold">PT</div></div></header>
    <main className="max-w-6xl mx-auto px-8 py-10"><div className="flex items-end justify-between gap-5"><div><div className="text-xs font-semibold text-indigo-600 uppercase tracking-[0.2em]">Agent platform</div><h1 className="mt-2 text-3xl font-bold tracking-tight">{tab === 'catalog' ? 'Find the right Agent for every workflow' : tab === 'workspace' ? 'Your Workspace' : 'Runtime activity'}</h1><p className="mt-2 text-slate-500 text-sm">{tab === 'catalog' ? 'Discover versioned capabilities, install with explicit permissions, and invoke through a governed Router.' : 'Owner-only view for ' + DEMO_WORKSPACE.workspaceId + '.'}</p></div>{tab === 'catalog' && <button className="hidden sm:flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500">Register Agent <ArrowRight size={15} /></button>}</div>
      {tab === 'catalog' && <><div className="mt-8 flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-3 py-2.5 shadow-sm max-w-xl"><Search size={16} className="text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by name, capability, or owner" className="flex-1 outline-none text-sm placeholder:text-slate-400" /><kbd className="rounded border border-slate-200 px-1.5 py-0.5 text-[10px] text-slate-400">⌘K</kbd></div><div className="mt-8 grid sm:grid-cols-3 gap-4"><Stat icon={<Grid2X2 size={17} />} label="Published agents" value={String(DEMO_AGENTS.filter((a) => a.status === 'published').length)} /><Stat icon={<ShieldCheck size={17} />} label="Enabled installs" value={String(DEMO_INSTALLATIONS.filter((i) => i.status === 'enabled').length)} /><Stat icon={<Zap size={17} />} label="Capabilities" value={String(new Set(DEMO_AGENTS.flatMap((a) => a.tags)).size)} /></div><div className="mt-8 grid md:grid-cols-2 xl:grid-cols-3 gap-5">{agents.map((agent) => <article key={agent.id + agent.version} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,0.05)] hover:-translate-y-0.5 hover:shadow-[0_12px_38px_rgba(15,23,42,0.1)] transition-all"><div className="flex items-start justify-between gap-3"><div className="h-10 w-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center"><Sparkles size={18} /></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${agent.status === 'published' ? 'bg-emerald-50 text-emerald-700' : agent.status === 'draft' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-500'}`}>{agent.status}</span></div><h2 className="mt-4 font-semibold text-lg">{agent.name}</h2><p className="mt-1 text-xs font-mono text-slate-400">{agent.id} · v{agent.version}</p><p className="mt-3 min-h-10 text-sm leading-relaxed text-slate-500">{agent.description}</p><div className="mt-4 flex flex-wrap gap-1.5">{agent.tags.map((tag) => <span key={tag} className="rounded-md bg-slate-50 px-2 py-1 text-[10px] text-slate-500">{tag}</span>)}</div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-xs text-slate-400">by {agent.owner}</span><button className="flex items-center gap-1 text-xs font-semibold text-indigo-600 hover:text-indigo-700">View card <ArrowRight size={13} /></button></div></article>)}</div></>}
      {tab === 'workspace' && <div className="mt-8 grid md:grid-cols-[1fr_1.5fr] gap-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><div className="text-xs text-slate-400">Active Workspace</div><div className="mt-1 font-mono text-sm">{DEMO_WORKSPACE.workspaceId}</div></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-semibold text-emerald-700">Owner</span></div><div className="mt-8 grid grid-cols-2 gap-3"><Fact label="Owner" value={DEMO_WORKSPACE.ownerId} /><Fact label="Updated" value={shortDate(DEMO_WORKSPACE.updatedAt)} /></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-semibold">Installed Agents</h2><button className="flex items-center gap-1 text-xs text-slate-500">Manage <ChevronDown size={13} /></button></div><div className="mt-4 divide-y divide-slate-100">{DEMO_INSTALLATIONS.filter((item) => item.status !== 'uninstalled').map((item) => <div key={item.installationId} className="flex items-center justify-between py-3"><div><div className="text-sm font-medium">{item.agentId}</div><div className="text-xs text-slate-400">Pinned {item.installedVersion}</div></div><span className={`text-xs ${item.status === 'enabled' ? 'text-emerald-600' : 'text-amber-600'}`}>{item.status}</span></div>)}</div></section></div>}
      {tab === 'activity' && <div className="mt-8 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-100 px-6 py-4"><Clock3 size={16} className="text-indigo-600" /><h2 className="font-semibold">Invocation and Ledger</h2></div><div className="p-6"><div className="rounded-xl bg-indigo-50 p-4 text-sm text-indigo-800"><CheckCircle2 size={16} className="inline mr-2" />Live Owner-only metadata reads are connected through Northbound API v4.</div><div className="mt-5 grid sm:grid-cols-2 gap-4"><Fact label="Invocation" value="POST /v4/workspaces/{id}/invocations" /><Fact label="Trace" value="GET /v4/workspaces/{id}/traces/{traceId}" /></div></div></div>}
    </main><DemoSwitcher current="saas" /></div>;
}

function Stat({icon, label, value}: {icon: ReactNode; label: string; value: string}) { return <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2 text-xs text-slate-500">{icon}{label}</div><div className="mt-2 text-2xl font-bold">{value}</div></div>; }
function Fact({label, value}: {label: string; value: string}) { return <div className="rounded-lg border border-slate-100 bg-slate-50 p-3"><div className="text-[10px] uppercase tracking-[0.15em] text-slate-400">{label}</div><div className="mt-1 truncate font-mono text-xs text-slate-700">{value}</div></div>; }
